# .github/workflows/ci.yml 

name: ML Model Training CI 

on: 
 	push: 
		branches: 
			- kernelridge # Trigger workflow on push to kernelridge branch 

jobs: 
	train-and-evaluate: 
		runs-on: ubuntu-latest 
		steps: 
			- name: Check out the code 
			uses: actions/checkout@v3 
			
			- name: Set up Python 
			uses: actions/setup-python@v4 
			with: 
				python-version: '3.13.7'
			
			- name: Install dependencies 
			run: | 
				python -m pip install --upgrade pip 
				pip install -r requirements.txt 
			
			- name: Run Decision Tree training 
			run: python train.py 

			- name: Run Kernel Ridge training
			run: python train2.py
